---
title: "Correlation vis"
author: "Frankie Fan"
date: '2022-07-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the packages
```{r}
library("corrplot")
library(readxl)
library(dplyr)
library(tidyverse)
```

## Read in the files
```{r}
Corr2017 <- read_csv("./Data/Corr2017.csv")
Corr2011 <- read_csv("./Data/Corr2011.csv")
```

```{r}
Corr2011 %>%
  filter(!row_number() %in% c(11:17)) %>% 
  select(-`...12`)
```
```{r}
plot <- ggplot(data = Corr2011, aes(x=Var1, y=Var2, fill=value, 
label= value))

plot + 
  geom_tile() +
  scale_fill_gradient2(low = "#132B43", high ="#56B1F7", mid = "white")
```



```{r}

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(Corr2011, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```




```{r}
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```