---
title: "Visualizations for soil growing seasons"
author: "Ari L"
date: '2022-06-28'
output:
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(sf)
library(ggplot2)
library(rgdal)

library(ggsn)
library(ggspatial)
```

read in the files #variables already loaded from dataProcessing-Soil.rmd
```{r}
surface_soil_monthly <- read_csv("./Data/soil_monthly.csv")
zim_district <- st_read("./shape60/gadm36_ZWE_2.shp")  


sub_soil_monthly <- read_csv("./Data/sub_soil_monthly.csv")
sub_soil_range <-read_csv("./Data/sub_soil_monthly_2016_2018.csv")

perc_soil_monthly <- read_csv("./Data/perc_soil_monthly.csv")
perc_soil_range <-read_csv("./Data/perc_soil_monthly_2016_2018.csv")
```
Rename cols to match
```{r}
zim_district <- rename(zim_district, District = NAME_2)
```


```{r}
zim_district <- zim_district %>% 
  select(District)

Surface_MonthlysoilbyDis <-full_join (zim_district, surface_soil_monthly, by = "District")
Sub_MonthlysoilbyDis <-full_join (zim_district, sub_soil_monthly, by = "District")
Perc_MonthlysoilbyDis <-full_join (zim_district, perc_soil_monthly, by = "District")
```




```{r}
grows <- list(Surface_MonthlysoilbyDis,Sub_MonthlysoilbyDis,Perc_MonthlysoilbyDis)
```



## 1. Monthly map for YearBegin 2011 and 2017
```{r}
growgraph1 <- function(df){
  grow1 <- df %>%
    filter(YearBegin == 2016 & MonthBegin == "10"|
          YearBegin == 2016 & MonthBegin == "11"|
          YearBegin == 2016 & MonthBegin == "12"|
          YearBegin == 2017 & MonthBegin == "01"|
          YearBegin == 2017 & MonthBegin == "02"|
          YearBegin == 2017 & MonthBegin == "03"|
          YearBegin == 2017 & MonthBegin == "04"|
          YearBegin == 2017 & MonthBegin == "05") %>%
    
   mutate(group = case_when(
          YearBegin == 2016 & MonthBegin == "10" ~"A",
          YearBegin == 2016 & MonthBegin == "11" ~"B",
          YearBegin == 2016 & MonthBegin == "12"~"C",
          YearBegin == 2017 & MonthBegin == "01"~"D",
          YearBegin == 2017 & MonthBegin == "02"~"E",
          YearBegin == 2017 & MonthBegin == "03"~"F",
          YearBegin == 2017 & MonthBegin == "04"~"G",
          YearBegin == 2017 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle("Max soil moisture in Zimbabwe - Growing season 1")
grow1
}
growgraph2 <- function(df){
  grow2 <- df %>%
    filter(YearBegin == 2017 & MonthBegin == "10"|
          YearBegin == 2017 & MonthBegin == "11"|
          YearBegin == 2017 & MonthBegin == "12"|
          YearBegin == 2018 & MonthBegin == "01"|
          YearBegin == 2018 & MonthBegin == "02"|
          YearBegin == 2018 & MonthBegin == "03"|
          YearBegin == 2018 & MonthBegin == "04"|
          YearBegin == 2018 & MonthBegin == "05") %>%

   mutate(group = case_when(
          YearBegin == 2017 & MonthBegin == "10" ~"A",
          YearBegin == 2017 & MonthBegin == "11" ~"B",
          YearBegin == 2017 & MonthBegin == "12"~"C",
          YearBegin == 2018 & MonthBegin == "01"~"D",
          YearBegin == 2018 & MonthBegin == "02"~"E",
          YearBegin == 2018 & MonthBegin == "03"~"F",
          YearBegin == 2018 & MonthBegin == "04"~"G",
          YearBegin == 2018 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle("Max soil moisture in Zimbabwe - Growing season 2")
grow2
}

```

```{r}
growgraph <- function(df){
growgraph1(df)
growgraph2(df)
}
```

```{r}
growgraph(Surface_MonthlysoilbyDis)
```



```{r}
growgraph1(Surface_MonthlysoilbyDis)
growgraph2(Surface_MonthlysoilbyDis)
growgraph1(Sub_MonthlysoilbyDis)
growgraph2(Sub_MonthlysoilbyDis)
growgraph1(Perc_MonthlysoilbyDis)
growgraph2(Perc_MonthlysoilbyDis)
```




