---
title: "NDVI Graphs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(tidyverse)
```
```{r}
NDVI_source <- read_csv("NDVI2000-2021.csv")
avg_NDVI <- NDVI_source %>% filter(Type== "Average")
```

# Barplot
```{r}
avg_NDVI %>%
  arrange(Precipitation) %>% # First sort by val. This sort the dataframe but NOT the factor levels
  mutate(District = factor(District, levels = District, ordered = T)) %>%   # This trick update the factor levels
  ggplot( aes(x=District, y=Precipitation)) + 
    geom_bar(stat = "identity") +
    coord_flip()
```

```{r}
# reorder is close to order, but is made to change the order of the factor levels.
avg_NDVI$District = with(avg_NDVI, reorder(District, Precipitation, mean))
 
avg_NDVI %>%
ggplot( aes(x=District, y=Precipitation)) + 
    geom_bar(stat = "identity") +
    labs(title="Plot of NDVI by District",x="District Name", y = "NDVI") + 
  theme(axis.text.y = element_text(size = 6)) + 
   scale_fill_hue(c = 40) +
  coord_flip()
  
```



```{r}
joined_zim %>%
arrange(desc(M0_k3)) %>%
ggplot(aes(x=reorder(District_name.x , M0_k3), y = M0_k3, fill = M0_k3)) +
geom_bar(stat="identity") + coord_flip() + labs(title="Plot of Adjusted Headcount Ratio per District",
x="District Name", y = "Adjusted HeadCount Ratio") + theme(axis.text.y = element_text(size = 6)) + guides(fill=guide_legend(title="AHR")) + scale_fill_viridis_c(breaks = c(0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40), option = "plasma", direction = -1)
```


