---
title: "Visualizations for soil growing seasons"
author: "Ari L"
date: '2022-06-28'
output:
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(sf)
library(ggplot2)
library(rgdal)

library(ggsn)
library(ggspatial)
library(leaflet)
```

read in the files #variables already loaded from dataProcessing-Soil.rmd
```{r}
surface_soil_monthly <- read_csv("./Data/soil_monthly.csv")
zim_district <- st_read("./shape60/gadm36_ZWE_2.shp")  


sub_soil_monthly <- read_csv("./Data/sub_soil_monthly.csv")
sub_soil_range <-read_csv("./Data/sub_soil_monthly_2016_2018.csv")

perc_soil_monthly <- read_csv("./Data/perc_soil_monthly.csv")
perc_soil_range <-read_csv("./Data/perc_soil_monthly_2016_2018.csv")
```
Rename cols to match
```{r}
zim_district <- rename(zim_district, District = NAME_2)
```


```{r}
zim_district <- zim_district %>% 
  select(District)

Surface_MonthlysoilbyDis <-full_join (zim_district, surface_soil_monthly, by = "District")
Sub_MonthlysoilbyDis <-full_join (zim_district, sub_soil_monthly, by = "District")
Perc_MonthlysoilbyDis <-full_join (zim_district, perc_soil_monthly, by = "District")
```


```{r}
SSM <- list(Surface_MonthlysoilbyDis,"Surface Soil Moisture")
SUSM <- list(Sub_MonthlysoilbyDis,"Sub-Surface Soil Moisture")
PSM <- list(Perc_MonthlysoilbyDis,"Percent Soil Moisture")
#listlist <-list(SSM,SUSM,PSM)
```

## 1. Monthly MAX maps for YearBegin  2017
```{r}
growgraph1 <- function(df,string){
  grow1 = df %>%
    filter(YearBegin == 2016 & MonthBegin == "10"|
          YearBegin == 2016 & MonthBegin == "11"|
          YearBegin == 2016 & MonthBegin == "12"|
          YearBegin == 2017 & MonthBegin == "01"|
          YearBegin == 2017 & MonthBegin == "02"|
          YearBegin == 2017 & MonthBegin == "03"|
          YearBegin == 2017 & MonthBegin == "04"|
          YearBegin == 2017 & MonthBegin == "05") %>%
    
   mutate(group = case_when(
          YearBegin == 2016 & MonthBegin == "10" ~"A",
          YearBegin == 2016 & MonthBegin == "11" ~"B",
          YearBegin == 2016 & MonthBegin == "12"~"C",
          YearBegin == 2017 & MonthBegin == "01"~"D",
          YearBegin == 2017 & MonthBegin == "02"~"E",
          YearBegin == 2017 & MonthBegin == "03"~"F",
          YearBegin == 2017 & MonthBegin == "04"~"G",
          YearBegin == 2017 & MonthBegin == "05"~ "H")
   ) %>%
leaflet() %>%
  addTiles()%>%
  addPolygons(color = ~mypal(as.numeric(MaxSoilMoisture)),
              weight = 0.5,
              smoothFactor = 0.2,
              fillOpacity = 0.5,) %>%
  facet_wrap(~group)
 grow1
```


```{r}
  Perc_MonthlysoilbyDis <- 
  Perc_MonthlysoilbyDis %>%
    filter(YearBegin == 2016 & MonthBegin == "10"|
          YearBegin == 2016 & MonthBegin == "11"|
          YearBegin == 2016 & MonthBegin == "12"|
          YearBegin == 2017 & MonthBegin == "01"|
          YearBegin == 2017 & MonthBegin == "02"|
          YearBegin == 2017 & MonthBegin == "03"|
          YearBegin == 2017 & MonthBegin == "04"|
          YearBegin == 2017 & MonthBegin == "05") %>%
    
   mutate(group = case_when(
          YearBegin == 2016 & MonthBegin == "10" ~"A",
          YearBegin == 2016 & MonthBegin == "11" ~"B",
          YearBegin == 2016 & MonthBegin == "12"~"C",
          YearBegin == 2017 & MonthBegin == "01"~"D",
          YearBegin == 2017 & MonthBegin == "02"~"E",
          YearBegin == 2017 & MonthBegin == "03"~"F",
          YearBegin == 2017 & MonthBegin == "04"~"G",
          YearBegin == 2017 & MonthBegin == "05"~ "H")
   )
write.csv(Perc_MonthlysoilbyDis,"./Data/PerSoil_2016_2017.csv")
   
```

## 1. Monthly mean maps for YearBegin  2017
```{r}
growgraph3 <- function(df,string){
  grow1 = df %>%
    filter(YearBegin == 2016 & MonthBegin == "10"|
          YearBegin == 2016 & MonthBegin == "11"|
          YearBegin == 2016 & MonthBegin == "12"|
          YearBegin == 2017 & MonthBegin == "01"|
          YearBegin == 2017 & MonthBegin == "02"|
          YearBegin == 2017 & MonthBegin == "03"|
          YearBegin == 2017 & MonthBegin == "04"|
          YearBegin == 2017 & MonthBegin == "05") %>%
    
   mutate(group = case_when(
          YearBegin == 2016 & MonthBegin == "10" ~"A",
          YearBegin == 2016 & MonthBegin == "11" ~"B",
          YearBegin == 2016 & MonthBegin == "12"~"C",
          YearBegin == 2017 & MonthBegin == "01"~"D",
          YearBegin == 2017 & MonthBegin == "02"~"E",
          YearBegin == 2017 & MonthBegin == "03"~"F",
          YearBegin == 2017 & MonthBegin == "04"~"G",
          YearBegin == 2017 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = AverageSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle(string)
grow1
}
growgraph4 <- function(df,string){
  grow2 = df %>%
    filter(YearBegin == 2017 & MonthBegin == "10"|
          YearBegin == 2017 & MonthBegin == "11"|
          YearBegin == 2017 & MonthBegin == "12"|
          YearBegin == 2018 & MonthBegin == "01"|
          YearBegin == 2018 & MonthBegin == "02"|
          YearBegin == 2018 & MonthBegin == "03"|
          YearBegin == 2018 & MonthBegin == "04"|
          YearBegin == 2018 & MonthBegin == "05") %>%

   mutate(group = case_when(
          YearBegin == 2017 & MonthBegin == "10" ~"A",
          YearBegin == 2017 & MonthBegin == "11" ~"B",
          YearBegin == 2017 & MonthBegin == "12"~"C",
          YearBegin == 2018 & MonthBegin == "01"~"D",
          YearBegin == 2018 & MonthBegin == "02"~"E",
          YearBegin == 2018 & MonthBegin == "03"~"F",
          YearBegin == 2018 & MonthBegin == "04"~"G",
          YearBegin == 2018 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = AverageSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle(string)
grow2
}
```

## 1. Monthly min for YearBegin 2017
```{r}
growgraph5 <- function(df,string){
  grow1 = df %>%
    filter(YearBegin == 2016 & MonthBegin == "10"|
          YearBegin == 2016 & MonthBegin == "11"|
          YearBegin == 2016 & MonthBegin == "12"|
          YearBegin == 2017 & MonthBegin == "01"|
          YearBegin == 2017 & MonthBegin == "02"|
          YearBegin == 2017 & MonthBegin == "03"|
          YearBegin == 2017 & MonthBegin == "04"|
          YearBegin == 2017 & MonthBegin == "05") %>%
    
   mutate(group = case_when(
          YearBegin == 2016 & MonthBegin == "10" ~"A",
          YearBegin == 2016 & MonthBegin == "11" ~"B",
          YearBegin == 2016 & MonthBegin == "12"~"C",
          YearBegin == 2017 & MonthBegin == "01"~"D",
          YearBegin == 2017 & MonthBegin == "02"~"E",
          YearBegin == 2017 & MonthBegin == "03"~"F",
          YearBegin == 2017 & MonthBegin == "04"~"G",
          YearBegin == 2017 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MinSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle(string)
grow1
}
growgraph6 <- function(df,string){
  grow2 = df %>%
    filter(YearBegin == 2017 & MonthBegin == "10"|
          YearBegin == 2017 & MonthBegin == "11"|
          YearBegin == 2017 & MonthBegin == "12"|
          YearBegin == 2018 & MonthBegin == "01"|
          YearBegin == 2018 & MonthBegin == "02"|
          YearBegin == 2018 & MonthBegin == "03"|
          YearBegin == 2018 & MonthBegin == "04"|
          YearBegin == 2018 & MonthBegin == "05") %>%

   mutate(group = case_when(
          YearBegin == 2017 & MonthBegin == "10" ~"A",
          YearBegin == 2017 & MonthBegin == "11" ~"B",
          YearBegin == 2017 & MonthBegin == "12"~"C",
          YearBegin == 2018 & MonthBegin == "01"~"D",
          YearBegin == 2018 & MonthBegin == "02"~"E",
          YearBegin == 2018 & MonthBegin == "03"~"F",
          YearBegin == 2018 & MonthBegin == "04"~"G",
          YearBegin == 2018 & MonthBegin == "05"~ "H")
   ) %>%
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MinSoilMoisture)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~group) +
  ggtitle(string)
grow2
}
```

```{r}
mypal <- colorNumeric(
  palette = "magma",
  domain = Surface_MonthlysoilbyDis$MaxSoilMoisture
)

mypal(c(100, 200, 300, 400, 500))
```
```{r}
growgraph2(Surface_MonthlysoilbyDis)
```


Graph max
```{r}
growgraph1(SSM[[1]],SSM[[2]])
growgraph2(SSM[[1]],SSM[[2]])
growgraph1(SUSM[[1]],SUSM[[2]])
growgraph2(SUSM[[1]],SUSM[[2]])
growgraph1(PSM[[1]],PSM[[2]])
growgraph2(PSM[[1]],PSM[[2]])
```
Graph mean
```{r}
growgraph3(SSM[[1]],SSM[[2]])
growgraph4(SSM[[1]],SSM[[2]])
growgraph3(SUSM[[1]],SUSM[[2]])
growgraph4(SUSM[[1]],SUSM[[2]])
growgraph3(PSM[[1]],PSM[[2]])
growgraph4(PSM[[1]],PSM[[2]])
```
Graph min
```{r}
growgraph5(SSM[[1]],SSM[[2]])
growgraph6(SSM[[1]],SSM[[2]])
growgraph5(SUSM[[1]],SUSM[[2]])
growgraph6(SUSM[[1]],SUSM[[2]])
growgraph5(PSM[[1]],PSM[[2]])
growgraph6(PSM[[1]],PSM[[2]])
```


```{r}
#```{r}
growgraph1(SSM[[1]],SSM[[2]])
growgraph2(SSM[[1]],SSM[[2]])
growgraph1(SUSM[[1]],SUSM[[2]])
growgraph2(SUSM[[1]],SUSM[[2]])
growgraph1(PSM[[1]],PSM[[2]])
growgraph2(PSM[[1]],PSM[[2]])
```growgraph1(Surface_MonthlysoilbyDis) 
#growgraph2(Surface_MonthlysoilbyDis)
#growgraph1(Sub_MonthlysoilbyDis)
#growgraph2(Sub_MonthlysoilbyDis)
#growgraph1(Perc_MonthlysoilbyDis)
#growgraph2(Perc_MonthlysoilbyDis)
```


```{r}
#grows <- list(Surface_MonthlysoilbyDis,Sub_MonthlysoilbyDis,Perc_MonthlysoilbyDis)
#names <- list("Surface Soil Moisture", "Sub-Surface Soil Moisture", "Percent Soil Moisture")
#listlist <- list(grows,names)
```

```{r}
#jim <- list(Surface_MonthlysoilbyDis,"Surface Soil Moisture")
```



