---
title: "Leaflet_Precipitation"
author: "JBN"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(leaflet)
library(ggplot2)
library(rgdal)
library(dplyr)
library(sf)
library(gpclib)
library(maptools)
library(ggpolypath)
```

read in csv file 
```{r}
PRECIP_Summer_2010_2011 <-read_csv(file = 'PRECIP_Summer_2010_2011.csv')
PRECIP_Summer_2011_2012 <-read_csv(file = 'PRECIP_Summer_2011_2012.csv')
PRECIP_Summer_2016_2017 <-read_csv(file = 'PRECIP_Summer_2016_2017.csv')
PRECIP_Summer_2017_2018 <-read_csv(file = 'PRECIP_Summer_2017_2018.csv')


```



```{r}
mypal <- colorNumeric(
  palette = "magma",
  domain = SummerPRECIP_2016_2017_MeanMap$MeanPRECIP
)

mypal(c(100, 200, 300, 400, 500))
```

### Mean (All Years and Months)
```{r}

Psummer_2010_2011_Joined <- full_join(zim_district,PRECIP_Summer_2010_2011, by = "District")

leaflet(Psummer_2010_2011_Joined) %>%
  addTiles()%>%
  addPolygons(color = ~mypal(as.numeric(MeanPRECIP)),
              weight = 0.5,
              smoothFactor = 0.2,
              fillOpacity = 0.5,
  )

```

### Min (All Years and Months)
 



### Max (All Years and Months)

