---
title: "MPI_2011"
author: "JBN"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###This Script will be used to read In MPI data from 2011 & 2017 

Imports 
```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(sf)
library(ggplot2)
library(rgdal)
```

read in the MPI Excel
```{r}
MPI_2011 <- read_excel("./2011_MPI_excerpt data.xlsx")
```

```{r}
head(MPI_2011)
```

Import Shape file into r (Change district 90 --> district 60)
```{r}
#file name: 0=boundary, 1=province, 2=district 
zim_boundary <- st_read("./gadm36_ZWE_shp/gadm36_ZWE_0.shp") 
zim_province <- st_read("./gadm36_ZWE_shp/gadm36_ZWE_1.shp")
zim_district <- st_read("./gadm36_ZWE_shp/gadm36_ZWE_2.shp")  
```
plot boundary, province, district 
```{r}
plot(zim_boundary)
plot(zim_province)
plot(zim_district)

```
Rename cols to match
```{r}
zim_district <- rename(zim_district, District_name = "NAME_2")
```


Get the IDs to match 
```{r}
zim_district <- zim_district %>% 
  arrange(District_name) %>% 
  mutate(District_ID = c(1:60))

joined_zim <-  full_join (zim_district,MPI_2011, by = "District_ID")
  
```


Mapping M_0
```{r}
ggplot() +
geom_sf(data = joined_zim, size = 1, color = "black", aes(fill = M0_k3)) +
ggtitle("Population at Severe Risk of Food Insecurity in Zimbabwe - 2011") + scale_fill_viridis_c()+
coord_sf()

```

