---
title: "RegionalViz"
author: "Ari L."
date: "7/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
library(dplyr)
library(moderndive)
library(readr)
library(tidyr)
library(lubridate)
library(stringr)
library(readxl)
library(dplyr)
library(tidyverse)
library(sf)
library(ggplot2)
library(rgdal)

library(ggsn)
library(ggspatial)

library(Hmisc)
```

read in the files 
```{r}
Ssoil_all <- read_csv("./regional_data/Ssoil_regional.csv")
Ssoil_g1617 <- read_csv("./regional_data/Ssoil_regional_g16_17.csv")
zim_district <- st_read("./shape60/gadm36_ZWE_2.shp")  

```


Now make some graphs
```{r}

#Another plot with two regions -- add more here
p <- ggplot(total, aes(newDate, y = value, color = variable)) + 
    geom_line(aes(y = sum_I, col = "Region I"), size=1.25) + 
    geom_line(aes(y = sum_IIA, col = "Region IIA"), size=1.25) +
    geom_line(aes(y = sum_IIB, col = "Region IIB"), size=1.25) +
    geom_line(aes(y = sum_III, col = "Region III"), size=1.25) +
    geom_line(aes(y = sum_IV, col = "Region IV"), size=1.25) +
    geom_line(aes(y = sum_V, col = "Region V"), size=1.25) + labs(color="Agri Regions") +
     xlab("2010-11 Growing Season") + ylab("Count of dry days (15 day window)") + 
     ggtitle("Sum of Dry Days within 15 days of Planting") +
     theme(plot.title = element_text(hjust = 0.5))

p

# Set axis limits c(min, max) on plot
 min <- as.Date("2010-10-1")
 max <- as.Date("2011-4-30")
 p + scale_x_date(limits = c(min, max)) 

 

```

