---
title: "Visualizations for EVI"
author: "Frankie Fan"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(sf)
library(ggplot2)
library(rgdal)

library(ggsn)
library(ggspatial)
```

read in the files [NOT NEEDED]
```{r}
#`EVI_monthly` <- read_csv("./Data/EVI_monthly.csv")
#AnnualEVI <- read_csv("./Data/EVI_annual.csv")
#zim_district <- st_read("./Shapefiles/Zim_D60.shp")  
#EVI_long <- read_csv("./Data/EVI_long.csv") 
```


```{r}
zim_district <- zim_district %>% 
  select(District)
 
PRECIP_district_2011 <-  full_join (zim_district, PRECIP_monthly_2011, by = "District")

PRECIP_district_2017 <-  full_join (zim_district, PRECIP_monthly_2017, by = "District")
```

Rename cols to match [NOT NEEDED]
```{r}
#zim_district <- rename(zim_district, District = NAME_2)
```

[Frankie code] [NOT NEEDED]
```{r}
zim_district <- zim_district %>% 
  select(District)

MonthlyEVIbyDis <-full_join (zim_district, `EVI_monthly`, by = "District")
```





## 1. Monthly map for Year 2011 and 2017 [Frankie code]
```{r}
# Maximum evi by month
MaxMonthlyEVI2011 <- MonthlyEVIbyDis %>% 
  filter(Year == 2011) %>% 
  arrange(Month) %>% 
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxEVI)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~Month) +
  ggtitle("Max EVI in Zimbabwe - 2011")
MaxMonthlyEVI2011



MaxMonthlyEVI2017 <- MonthlyEVIbyDis %>% 
  filter(Year == 2017) %>% 
  arrange(Month) %>% 
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxEVI)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~Month) +
  ggtitle("Max EVI in Zimbabwe - 2011")
MaxMonthlyEVI2017
```


Josue's Adaptation
```{r}
# Maximum PRECIP by month
#2011
MaxMonthlyPRECIP_2011 <- PRECIP_district_2011 %>% 
  filter(Year == 2011) %>% 
  arrange(Month) %>% 
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxPRECIP)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~Month) +
  ggtitle("Max PRECIP in Zimbabwe - 2011")
MaxMonthlyPRECIP_2011

#2017
MaxMonthlyPRECIP_2017 <- PRECIP_district_2017 %>% 
  filter(Year == 2017) %>% 
  arrange(Month) %>% 
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxPRECIP)) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  facet_wrap(~Month) +
  ggtitle("Max PRECIP in Zimbabwe - 2017")
MaxMonthlyPRECIP_2017
```



## 2a. Distribution of EVI from 2011-2017 [Frankie code]
```{r}
Precipitation_long %>% 
  filter(Year == 2011:2017) %>% 
  ggplot(aes(x = Year, y = Precipitation, fill = as.factor(Year))) + 
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape = 8,
               size = 2, color = "white") +
  scale_fill_brewer(palette="Set1", name = "Year") +
  labs(title = "Distribution of PRECIP in Zimbabwe, Year 2011-2017") 

```


## 2b. Distribution of NDVI in 2011 and 2017 [Frankie code]
```{r}
PRECIP_monthly %>% 
  filter( Year == 2011|Year == 2017) %>% 
  gather(Type, Precipitation, AveragePRECIP:MinPRECIP) %>% 
  ggplot(aes(x = Type, y = Precipitation, fill = Type)) +
  scale_fill_brewer(palette="Set3", name = "Type") +
  facet_wrap(~Year)+
  geom_boxplot() +
  labs(title = "Distribution of PRECIP, Year 2011 & 2017") +
    xlab("Statistics") +
    ylab("Precipitation")

```


## 3. map for EVI in March in 2011 and 2017 [Frankie code]
```{r, visualization for March}

MaxMarch <-  PRECIP_monthly %>% 
  filter(Year == 2011|Year == 2017, Month == "03") %>% 
  ggplot() +
  geom_sf(size = 1, color = "black", aes(fill = MaxPRECIP)) +
  facet_wrap(~Year) +
  coord_sf() +
  scale_fill_viridis_c(option = "G", direction = -1) +
  ggtitle("Maximum PRECIP in Zimbabwe - March")
MaxMarch
```



