---
title: "Zimbabwe Project Skeleton"
author: "Leonard-Allen"
Last Update: 6/10/2022
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
    theme: readable
  pdf_document:
    toc: yes
    toc_depth: '4'
colorlinks: yes
urlcolor: blue
linkcolor: blue
citecolor: blue
anchorcolor: blue
toccolor: blue
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Using Remotely Sensed Data for Social & Economic Decision Making in Zimbabwe

### Data Science for the Public Good Program

### Virginia Tech

### Department of Agricultural and Applied Economics

# 1. Overview

## 1.1 Project Overview

## 1.2 Project Outcomes

## 1.3 About Zimbabwe

# 2. Data & Methodology

# 2.1 Data 

## 2.1.1 PICES Data 

The data come from two nationally representative household surveys, called the PICES, conducted by ZIMSTAT: first, from June 2011 to May 2012, and second, from January to December 2017. The PICES surveys are well suited to construct multidimensional poverty indices because they include information at the household and individual levels, and they are collected repeatedly. The surveys were conducted in the eight provinces of Zimbabwe and in the cities of Harare and Bulawayo. The number of usable observations (households) is 29,748 in 2011--2012 (23,843 rural and 5,905 urban) and 31,193 in 2017 (25,525 rural and 5668 urban). Survey weights and household size are employed to obtain national, provincial, and rural-urban representation. Both survey instruments are virtually identical across the two waves. They include information on household demographics, education, employment, healthcare, migration, housing characteristics, assets ownership, access to services, and agricultural activities.

## 2.1.2 Variables

## 2.1.3 Resources

-   **Google Earth Engine** : Google Earth Engine combines a multi-petabyte catalog of satellite imagery and geospatial datasets with planetary-scale analysis capabilities and makes it available for scientists, researchers, and developers to detect changes, map trends, and quantify differences on the Earth's surface. We used it to collect data on NDVI, EVI, precipitation and Soil moisture in Zimbabwe.
-   **Google Maps.** Google Maps is a comprehensive web mapping service created by Google. Its goal is to provide an interactive map of all the geographical contents of the world. This resource has a variety of uses, ranging from examining all service locations within a city to finding the quickest route between locations. It provides data at latitude and longitude level. We used Google Maps to visualize weather information behind the Google Earth Engine.

# 2.2 Methodology

A brief overview of the Mathematics behind the Multidimensional Poverty Index

## 2.2.1 Socio-Demographic information

## 2.2.2 Remote Sensing

## 2.2.3 Selected Indicies

- NDVI

- EVI

- Soil

- Precipitation


# 3. Spatial visualization of Indices 

# 4. Spatial visualization of MPI

# 5. Link between MPI & Remote Sensed Data

# 6. Policy Implications/Takeaways

# 7. Our Team

## Team

### VT Data Science for the Public Good

The Data Science for the Public Good (DSPG) Young Scholars program is a summer immersive program offered by the [Virginia Tech Department of Agricultural and Applied Economics](https://aaec.vt.edu/index.html) In its second year, the program engages students from across the country to work together on projects that address state, federal, and local government challenges around critical social issues relevant in the world today. DSPG young scholars conduct research at the intersection of statistics, computation, and the social sciences to determine how information generated within every community can be leveraged to improve quality of life and inform public policy. For more information on program highlights, how to apply, and our annual symposium, please visit [the official VT DSPG website](https://aaec.vt.edu/content/aaec_vt_edu/en/academics/undergraduate/beyond-classroom/dspg.html#select=1.html).

### DSPG **Team Members**

### Graduate Fellows

[LEONARD-ALLEN QUAYE](https://aaec.vt.edu/people/graduatestudents/index/quaye-leonard-allen.html) (Virginia Tech, PhD Agricultural and Applied Microeconomics)

[POONAM TAJANPURE](https://www.bse.vt.edu/people/grad-students/poonam-tajanpure.html) (Virginia Tech, PhD BSE)

### Undergraduate Interns

[ARI LIVERPOOL](https://www.linkedin.com/in/ari-l-12b151123/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3B5WMwWerMTvefiu%2Fq85Z5mw%3D%3D) (Applied Economics Major, Data and Decisions minor; Virginia Tech)

FRANKIE FAN (Math and Data Science Double Major)

[JOSUE NAVARRETE](https://www.linkedin.com/in/josue-navarrete-36a6321b4/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_connections%3B5WMwWerMTvefiu%2Fq85Z5mw%3D%3D) (Computer Science Major)

### Faculty Members

[SUSAN CHEN](https://aaec.vt.edu/people/faculty/chen-susan.html) (Virginia Tech, Agricultural and Applied Microeconomics);

[BRIANNA POSADAS](https://www.linkedin.com/in/briannaposadas/) (Virginia Tech School of Plant and Environmental Sciences)

[JEFFREY ALWANG](https://aaec.vt.edu/people/faculty/alwang-jeffrey.html) (Virginia Tech, Agricultural and Applied Microeconomics);


### Project Stakeholders

THE WORLD BANK

### Acknowledgement

We would like to thank TAWANDA CHINGOZHA (STELLENBOSCH UNIVERSITY) for his support on this project.

### Disclaimer:

This project is an academic exercise conducted by VT-Data Science for the Public Good. The findings, interpretations, and conclusions expressed here do not necessarily reflect the views of the World Bank or the Zimbabwe Statistical Agency.
